config/routes.rb
VenueManagement::Application.routes.draw do
  root :to => "venues#index"
 
  resources :venues do
    resources :contacts
    resources :styles
    resources :meeting_rooms
  end

  match 'api/search_venues(.:format)'
  match 'api/show_venue(.:format)'

end

app/models/meeting_room.rb
class MeetingRoom < ActiveRecord::Base
  belongs_to :venue
end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  # GET /meeting_rooms
  # GET /meeting_rooms.xml
  def index
    @venue = Venue.find(params[:venue_id])
    @meeting_rooms = @venue.meeting_room

    respond_to do |format|
      format.html #index.html.erb
      format.xml { render :xml => @meeting_rooms }
    end
  end
  
  # GET /meeting_rooms/1
  # GET /meeting_rooms/1.xml
  def show
    @venue = Venue.find(params[:venue_id])
    @meeting_room = @venue.meeting_room.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @meeting_room }
    end
  end

  # GET /meeting_rooms/new
  # GET /meeting_rooms/new.xml
  def new
    @venue = Venue.find(params[:venue_id])
    @meeting_room = @venue.meeting_room.new

    respond_to do |format|
      format.html #new.html.erb
    end
  end
  
   # GET /meeting_rooms/1/edit
  def edit
    @venue = Venue.find(params[:venue_id])
    @meeting_room = @venue.meeting_room.find(params[:id])
  end
  
  # POST /meeting_rooms
  # POST /meeting_rooms.xml
  def create
    @venue = Venue.find(params[:venue_id])
    @meeting_room = @venue.meeting_room.new(params[:meeting_room])
    
    respond_to do |format|
      if @meeting_room.save
        format.html { redirect_to(venue_meeting_rooms_path, :notice => 'meeting_room was successfully created.') }
      else
        format.html {render :action => "new" }
      end 
    end
  end
  
  # POST /meeting_rooms
  # POST /meeting_rooms.xml
  def update
    @venue = Venue.find(params[:venue_id])
    @meeting_room = @venue.meeting_room.find(params[:id])
        
    respond_to do |format|
      if @meeting_room.update_attributes(params[:meeting_room])
        #format.html { redirect_to(venue_meeting_rooms_path, :notice => "meeting_room was successfully updated.")}
        format.html { redirect_to(venue_meeting_rooms_path, :notice => "meeting_room was successfully updated.")}
        format.xml { head :ok }
       else
         format.html { render :action => "edit"}
         format.xml { render :xml => @meeting_room.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  #DELETE /meeting_rooms/1
  #DELETE /meeting_rooms/1.xml
  def destroy
    @venue = Venue.find(params[:venue_id])
    @meeting_room = @venue.meeting_room.find(params[:id])
    @meeting_room.destroy
    
    respond_to do |format|
      format.html { redirect_to(venue_meeting_rooms_url)}
      format.xml { head :ok } 
    end
  end
end

app/helpers/meeting_rooms_helper.rb
module MeetingRoomsHelper
end

app/views/meeting_rooms/_form.html.erb
<%= form_for [@venue, @meeting_room] do |f| %>
  <% if @meeting_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting_room.errors.count, "error") %> prohibited this Meeting Room from being saved:</h2>

      <ul>
      <% @meeting_room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th width="130">Room Name:</th>
    <td><%= f.text_field :room_name, :size => 50 %></td>
  </tr>
  <tr>
    <th>Suit:</th>
    <td><%= f.text_field :suite, :size => 30 %></td>
  </tr>
  <tr>
    <th>Floor:</th>
    <td><%= f.text_field :floor, :size => 30 %></td>
  </tr>
  <tr>
    <th>Lift:</th>
    <td><%= f.select :lift, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Theatre:</th>
    <td><%= f.text_field :theatre, :size => 10 %></td>
  </tr>
  <tr>
    <th>Classroom:</th>
    <td><%= f.text_field :classroom, :size => 10 %></td>
  </tr>
  <tr>
    <th>Boardroom:</th>
    <td><%= f.text_field :boardroom, :size => 10 %></td>
  </tr>
  <tr>
    <th>U-shape:</th>
    <td><%= f.text_field :ushape, :size => 10 %></td>
  </tr>
  <tr>
    <th>Cabaret:</th>
    <td><%= f.text_field :cabaret, :size => 10 %></td>
  </tr>
  <tr>
    <th>Dinner / Dance:</th>
    <td><%= f.text_field :dinner_dance, :size => 10 %></td>
  </tr>
  <tr>
    <th>Lunch / Dinner:</th>
    <td><%= f.text_field :lunch_dinner, :size => 10 %></td>
  </tr>
  <tr>
    <th>Reception:</th>
    <td><%= f.text_field :reception, :size => 10 %></td>
  </tr>
  <tr>
    <th>Length:</th>
    <td><%= f.text_field :length, :size => 10 %>m</td>
  </tr>
  <tr>
    <th>Width:</th>
    <td><%= f.text_field :width, :size => 10 %>m</td>
  </tr>
  <tr>
    <th>Area:</th>
    <td><%= f.text_field :area, :size => 10 %>m²</td>
  </tr>
  <tr>
    <th>Max Height:</th>
    <td><%= f.text_field :max_height, :size => 10 %>m</td>
  </tr>
  <tr>
    <th>Min Height:</th>
    <td><%= f.text_field :min_height, :size => 10 %>m</td>
  </tr>
  <tr>
    <th>Door Height:</th>
    <td><%= f.text_field :door_height, :size => 10 %>m</td>
  </tr>
  <tr>
    <th>Door Width:</th>
    <td><%= f.text_field :door_width, :size => 10 %>m</td>
  </tr>
  <tr>
    <th>Tungsten:</th>
    <td><%= f.select :tungsten, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Fluorescent:</th>
    <td><%= f.select :fluorescent, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Halogen:</th>
    <td><%= f.select :halogen, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Dimmers:</th>
    <td><%= f.select :dimmers, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Controls:</th>
    <td><%= f.select :controls, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Blackout:</th>
    <td><%= f.select :blackout, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Windows:</th>
    <td><%= f.select :windows, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Sound System:</th>
    <td><%= f.select :sound_system, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Air Conditioning:</th>
    <td><%= f.select :air_conditioning, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Phase:</th>
    <td><%= f.select :phase, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Sockets:</th>
    <td><%= f.text_field :sockets, :size => 10 %></td>
  </tr>
  <tr>
    <th>Telephone Points:</th>
    <td><%= f.text_field :telephone_points, :size => 10 %></td>
  </tr>
  <tr>
    <th>&nbsp;</th>
    <th><%= f.submit %> </th>
  </tr>
</table>
<% end %>

app/views/meeting_rooms/edit.html.erb
<h1>Edit Meeting Room</h1>

<%= render 'form' %>

app/views/meeting_rooms/index.html.erb
<h1>Meeting rooms: <%= link_to @venue.name, venue_path(@venue) %></h1>
<table>
	<tr>
		<th colspan="5" style="text-align:right"><%= link_to 'Add New Meeting Room', new_venue_meeting_room_path %></th>
	</tr>
	<tr>
		<th>Room Name</th>
		<th>Action</th>
	</tr>
	<%- for meeting_room in @meeting_rooms %>
	<tr>
		<td><%= link_to meeting_room.room_name, [@venue, meeting_room] %></td>
		<td><%= button_to 'Delete', [@venue, meeting_room], :method => :delete, :confirm => "you sure?" %></td>
	</tr>
	<%- end %>
</table>

app/views/meeting_rooms/new.html.erb
<h1>New Meeting Room</h1>

<%= render 'form' %>

app/views/meeting_rooms/show.html.erb
<h1><%= link_to @venue.name, venue_path(@venue) %>: <%= @meeting_room.room_name %></h1>
<p id="notice"><%= notice %></p>

<table>
  <tr>
  	<th width="130">Room Name:</th>
    <td><%= @meeting_room.room_name %> <%= link_to '(edit)', edit_venue_meeting_room_path(@venue, @meeting_room) %></td>
  </tr>
  <tr>
  	<th>Suite:</th>
    <td><%= @meeting_room.suite %></td>
  </tr>
  <tr>
  	<th>Floor:</th>
    <td><%= @meeting_room.floor %></td>
  </tr>
  <tr>
  	<th>Lift:</th>
    <td><%= @meeting_room.lift? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Theatre:</th>
    <td><%= @meeting_room.theatre %></td>
  </tr>
  <tr>
  	<th>Classroom:</th>
    <td><%= @meeting_room.classroom %></td>
  </tr>
  <tr>
  	<th>Boardroom:</th>
    <td><%= @meeting_room.boardroom %></td>
  </tr>
  <tr>
  	<th>U-shape:</th>
    <td><%= @meeting_room.ushape %></td>
  </tr>
  <tr>
  	<th>Cabaret:</th>
    <td><%= @meeting_room.cabaret %></td>
  </tr>
  <tr>
    <th>Dinner / Dance</th>
    <td><%= @meeting_room.dinner_dance %></td>
  </tr>
  <tr>
  	<th>Lunch / Dinner</th>
    <td><%= @meeting_room.lunch_dinner %></td>
  </tr>
  <tr>
  	<th>Reception</th>
    <td><%= @meeting_room.reception %></td>
  </tr>
  <tr>
  	<th>Length</th>
    <td><%= @meeting_room.length %>m</td>
  </tr>
  <tr>
  	<th>Width</th>
    <td><%= @meeting_room.width %>m</td>
  </tr>
  <tr>
  	<th>Area</th>
    <td><%= @meeting_room.area %>m²</td>
  </tr>
  <tr>
  	<th>Max Height</th>
    <td><%= @meeting_room.max_height %>m</td>
  </tr>
  <tr>
  	<th>Min Height</th>
    <td><%= @meeting_room.min_height %>m</td>
  </tr>
  <tr>
  	<th>Door Height</th>
    <td><%= @meeting_room.door_height %>m</td>
  </tr>
  <tr>
  	<th>Door Width</th>
    <td><%= @meeting_room.door_width %>m</td>
  </tr>
  <tr>
  	<th>Tungsten</th>
    <td><%= @meeting_room.tungsten? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Fluorescent</th>
    <td><%= @meeting_room.fluorescent? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Halogen</th>
    <td><%= @meeting_room.halogen? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Dimmers</th>
    <td><%= @meeting_room.dimmers? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Controls</th>
    <td><%= @meeting_room.controls? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Blackout</th>
    <td><%= @meeting_room.blackout? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Windows</th>
    <td><%= @meeting_room.windows? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Sound System:</th>
    <td><%= @meeting_room.sound_system? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Air Conditioning</th>
    <td><%= @meeting_room.air_conditioning? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Phase</th>
    <td><%= @meeting_room.phase? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
  	<th>Sockets</th>
    <td><%= @meeting_room.sockets %></td>
  </tr>
  <tr>
  	<th>Telephone Points</th>
    <td><%= @meeting_room.telephone_points %></td>
  </tr>
  <tr>
    <th>Delete:</th>
    <td><%= button_to 'Delete', [@venue, @meeting_room], :method => :delete, :confirm => "you sure?" %></td>
  </tr>
</table>