config/routes.rb
VenueManagement::Application.routes.draw do
  root :to => "venues#index"
 
  resources :venues do
    resources :contacts
    resources :styles
    resources :meeting_rooms
  end

  match 'api/search_venues(.:format)'
  match 'api/show_venue(.:format)'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :contact
  has_many :attraction
  has_many :nearby_facility
  has_many :style
  has_many :meeting_room
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # GET /venues
  # GET /venues.xml
  def index
    @search = Venue.search(params[:search])
    @venues = @search.page(params[:page]).per(20)
    @styles = Style.select("distinct style").order("style asc")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.xml
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.xml
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.xml
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to(@venue, :notice => 'Venue was successfully created.') }
        format.xml  { render :xml => @venue, :status => :created, :location => @venue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.xml
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to(@venue, :notice => 'Venue was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.xml
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to(venues_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th width="130">Venue Name:</th>
    <td><%= f.text_field :name, :size => 50 %></td>
  </tr>
  <tr>
    <th>Address:</th>
    <td><%= f.text_area :address, :style => "height:100px"  %></td>
  </tr>
  <tr>
    <th>Postcode:</th>
    <td><%= f.text_field :postcode, :size => 10 %></td>
  </tr>
  <tr>
    <th>Telephone:</th>
    <td><%= f.text_field :telephone, :size => 30 %></td>
  </tr>
  <tr>
    <th>Fax:</th>
    <td><%= f.text_field :fax, :size => 30 %></td>
  </tr>
  <tr>
    <th>Website:</th>
    <td><%= f.text_field :website, :size => 30 %></td>
  </tr>
  <tr>
    <th>Delegate rates:</th>
    <td>£<%= f.text_field :delegate_rates, :size => 5 %></td>
  </tr>
  <tr>
    <th>Room hire rates:</th>
    <td>£<%= f.text_field :room_hire_rates, :size => 5 %></td>
  </tr>
  <tr>
    <th>Meeting capacity:</th>
    <td><%= f.text_field :meeting_capacity, :size => 5 %></td>
  </tr>
  <tr>
    <th>Catering capacity:</th>
    <td><%= f.text_field :catering_capacity, :size => 5 %></td>
  </tr>
  <tr>
    <th>No bedrooms:</th>
    <td><%= f.text_field :no_bedrooms, :size => 5 %></td>
  </tr>
  <tr>
    <th>Disabled Access:</th>
    <td><%= f.select :disabled_access, [['Yes','true'],['No','false']] %></td>
  </tr>
  <tr>
    <th>Longitude:</th>
    <td><%= f.text_field :lan, :size => 5 %></td>
  </tr>
  <tr>
    <th>latitude:</th>
    <td><%= f.text_field :lat, :size => 5 %></td>
  </tr>
  <tr>
    <th>image:</th>
    <td><%= f.text_field :image, :size => 30 %></td>
  </tr>
  <tr>
    <th>date__venue:</th>
    <td><%= f.text_field :date__venue, :size => 30 %></td>
  </tr>
  <tr>
    <th>Commission:</th>
    <td><%= f.text_field :commission, :size => 5 %></td>
  </tr>
  <tr>
    <th>Notes:</th>
    <td><%= f.text_area :notes, :style => "width:780px;height:100px" %></td>
  </tr>
  <tr>
    <th>&nbsp;</th>
    <th><%= f.submit %> </th>
  </tr>
</table>
<% end %>

app/views/venues/edit.html.erb
<h1>Updating <%= @venue.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> | <%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<div class="span-18">
<h1>Listing all Venues</h1>
<%= paginate @venues %>
<table>
	<tr>
		<th colspan="7" style="text-align:right"><%= link_to 'Add New Venue', new_venue_path %></th>
	</tr>
	<tr>
		<th><%= sort_link @search, :name, "Venue Name" %></th>
		<th><%= sort_link @search, :meeting_capacity, "Meeting Capacity", :default_order => :desc %></th>
		<th><%= sort_link @search, :catering_capacity, "Catering Capacity", :default_order => :desc %></th>
		<th><%= sort_link @search, :room_hire_rates, "Room Hire Rates", :default_order => :asc %></th>
		<th>Styles</th>
    <th>Lat</th>
    <th>Lon</th>
    <th>Image</th>
    <th>date__venue</th>
		<th>Meeting<br>Rooms</th>
		<th>Action</th>
	</tr>
	<%- for venue in @venues %>
	<tr>
		<td><%= link_to venue.name, venue_path(venue) %></td>
		<td><%= venue.meeting_capacity %></td>
		<td><%= venue.catering_capacity %></td>
		<td><%= venue.room_hire_rates %></td>
		<td>
		  <%= link_to venue.style.size, venue_styles_path(venue) %>
		</td>
    <td>
      <%= venue.lan %>
    </td>
    <td>
      <%= venue.lat %>
    </td>
    <td>
      <%= image_tag venue.image.to_s, :alt => "image venues", :size => "100x100" %></td>
    </td>
    <td>
      <%= venue.date__venue.strftime("%Y-%m-%d") if venue.date__venue.present? %>
    </td>
		<td>
		  <%= link_to venue.meeting_room.size, venue_meeting_rooms_path(venue) %>
		</td>
		<td><%= link_to 'Edit', edit_venue_path(venue) %></td>
	</tr>
	<%- end %>
</table>

<%= paginate @venues %>
</div>
<div class="span-4 box last">
<h2>Search</h2>
<%= form_for @search do |f| %>
	<%= f.label :name_contains %>
	<%= f.text_field :name_contains, :size => 25 %><br />
	<%= f.label :postcode_contains %>
	<%= f.text_field :postcode_contains, :size => 25 %><br />
	<%= f.label :city_contains %>
	<%= f.text_field :city_contains, :size => 25 %><br />
	<%= f.label :county_contains %>
	<%= f.text_field :county_contains, :size => 25 %><br />
	<%= f.label :style_style_in, 'Style type' %>
    <ul style="list-style-type:none;margin-left:0;padding-left:0">
    <% f.collection_checks :style_style_in, @styles, :style, :style, :class => 'headcheck' do |check| %>
    	<li><%= check.box %> <%= check.label %></li>
	<% end %>
	</ul>
	<%= f.label :catering_capacity_gt %>
	<%= f.number_field :catering_capacity_gt, :size => 25 %><br />
	<%= f.label :meeting_capacity_gt %>
	<%= f.number_field :meeting_capacity_gt, :size => 25 %><br />
	<%= f.label :room_hire_rates_lt %>
	<%= f.number_field :room_hire_rates_lt, :size => 25 %><br />
	<%= f.submit "Search" %>
<% end %>
</div>

app/views/venues/new.html.erb
<h1>New Venue</h1>
<%= render 'form' %>

app/views/venues/show.html.erb
<script type="text/javascript">

var map = null;
var geocoder = null;

function showAddress(address, name) {
  if (geocoder) {
    geocoder.getLatLng(
      address,
      function(point) {
        if (!point) {
          alert(address + " not found");
        } else {
          map.setCenter(point, 13);
          var marker = new GMarker(point);
          map.addOverlay(marker);
          map.setUIToDefault();

          // As this is user-generated content, we display it as
          // text rather than HTML to reduce XSS vulnerabilities.
          marker.openInfoWindowHtml(name);
        }
      }
    );
  }
}

function initialize() {
  if (GBrowserIsCompatible()) {
    map = new GMap2(document.getElementById("map_canvas"));
    geocoder = new GClientGeocoder();
    showAddress("<%= @venue.address %>", "<strong><%= @venue.name %></strong><br><%= @venue.address %>")
  }
}

</script>
<h1><%= link_to 'Venues', venues_path() %>: <%= @venue.name %></h1>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th width="130">Venue:</th>
    <td><%= @venue.name %> <%= link_to '(edit)', edit_venue_path(@venue) %></td>
  </tr>
  <tr>
    <th>Address:</th>
    <td><%= @venue.address %></td>
  </tr>
  <tr>
    <th>Postcode:</th>
    <td><%= @venue.postcode %></td>
  </tr>
  <tr>
    <th>Telephone:</th>
    <td><%= @venue.telephone %></td>
  </tr>
  <tr>
    <th>Fax:</th>
    <td><%= @venue.fax %></td>
  </tr>
  <tr>
    <th>Website:</th>
    <td><a href="<%= @venue.website %>"><%= @venue.website %></a></td>
  </tr>
  <tr>
    <th>Delegate rates:</th>
    <td>From £<%= @venue.delegate_rates %></td>
  </tr>
  <tr>
    <th>Room hire rates:</th>
    <td>£<%= @venue.room_hire_rates %></td>
  </tr>
  <tr>
    <th>Meeting capacity:</th>
    <td><%= @venue.meeting_capacity %></td>
  </tr>
  <tr>
    <th>Catering capacity:</th>
    <td><%= @venue.catering_capacity %></td>
  </tr>
  <tr>
    <th>No bedrooms:</th>
    <td><%= @venue.no_bedrooms %></td>
  </tr>
  <tr>
    <th>Disabled Access:</th>
    <td><%= @venue.disabled_access? ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
    <th class="commission">Commission:</th>
    <td class="commission"><%= @venue.commission %></td>
  </tr>
  <tr>
    <th>Lat:</th>
    <td><%= @venue.lat %></td>
  </tr>
  <tr>
    <th>Lan:</th>
    <td><%= @venue.lan %></td>
  </tr>
  <tr>
    <th>image:</th>
    <td><%= image_tag @venue.image.to_s, :alt => "image venues" %></td>
  </tr>
  <tr>
    <th>Date venue:</th>
    <td><%= @venue.date__venue %></td>
  </tr>
  <tr>
    <th>Notes:</th>
    <td><%= @venue.notes %></td>
  </tr>
  <tr>
    <th><%= link_to "Contacts:", venue_contacts_path(@venue) %></th>
    <td>
       <%- for contact in @venue.contact -%>
       <%= link_to contact.contact_name, [@venue, contact] %> — <%= contact.contact_role %><br>
       <%- end -%>
    </td>
  </tr>
  <tr>
    <th><%= link_to "Meeting Rooms:", venue_meeting_rooms_path(@venue) %></th>
    <td>
      <table border="0">
      <tr>
        <th>Room Name:</th>
        <th>Theatre:</th>
        <th>Lunch/Dinner:</th>
        <th>Dinner/Dance:</th>
        <th>Length:</th>
        <th>Width:</th>
        <th>Area:</th>
      </tr>
      <%- for room in @venue.meeting_room -%>
      <tr>
        <td><%= link_to room.room_name, [@venue, room] %></td>
        <td><%= room.theatre %></td>
        <td><%= room.lunch_dinner %></td>
        <td><%= room.dinner_dance %></td>
        <td><%= room.length %>m</td>
        <td><%= room.width %>m</td>
        <td><%= room.area %>m<sup>2</sup></td>
      </tr>
      <%- end -%>
      </table>
    </td>
  </tr>
  <tr>
    <th><%= link_to "Styles:", venue_styles_path(@venue) %></th>
    <td>
      <%- for style in @venue.style -%>
      <%= link_to style.style, [@venue, style] %><br>
      <%- end -%>
    </td>
  </tr>
</table>
<div id="map_canvas" style="width: 950px; height: 300px"></div>
<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>