config/routes.rb
VenueManagement::Application.routes.draw do
  root :to => "venues#index"
 
  resources :venues do
    resources :contacts
    resources :styles
    resources :meeting_rooms
  end

  match 'api/search_venues(.:format)'
  match 'api/show_venue(.:format)'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :venue
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.xml
  def index
    @venue = Venue.find(params[:venue_id])
    @contacts = @venue.contact
    
    respond_to do |format|
      format.html #index.html.erb
      format.xml { render :xml => @contacts }
    end
  end
  
  # GET /contacts/1
  # GET /contacts/1.xml
  def show
    @venue = Venue.find(params[:venue_id])
    @contact = @venue.contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @venue = Venue.find(params[:venue_id])
    @contact = @venue.contact.new

    respond_to do |format|
      format.html #new.html.erb
    end
  end
  
   # GET /contacts/1/edit
  def edit
    @venue = Venue.find(params[:venue_id])
    @contact = @venue.contact.find(params[:id])
  end
  
  # POST /contacts
  # POST /contacts.xml
  def create
    @venue = Venue.find(params[:venue_id])
    @contact = @venue.contact.new(params[:contact])
    
    respond_to do |format|
      if @contact.save
        format.html { redirect_to(venue_contacts_path, :notice => 'Contact was successfully created.') }
      else
        format.html {render :action => "new" }
      end 
    end
  end
  
  # POST /contacts
  # POST /contacts.xml
  def update
    @venue = Venue.find(params[:venue_id])
    @contact = @venue.contact.find(params[:id])
        
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        #format.html { redirect_to(venue_contacts_path, :notice => "Contact was successfully updated.")}
        format.html { redirect_to(venue_contacts_path, :notice => "Contact was successfully updated.")}
        format.xml { head :ok }
       else
         format.html { render :action => "edit"}
         format.xml { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  #DELETE /contacts/1
  #DELETE /contacts/1.xml
  def destroy
    @venue = Venue.find(params[:venue_id])
    @contact = @venue.contact.find(params[:id])
    @contact.destroy
    
    respond_to do |format|
      format.html { redirect_to(venue_contacts_url)}
      format.xml { head :ok } 
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for [@venue, @contact] do |f| %>
	
	<% if @contact.errors.any? %>
		<div id="error_explanation">
			
			<h2>Error occurred</h2>
		</div>
	<% end %>
	
<div class="field">
	<%= f.label :contact_name%>
	<%= f.text_field :contact_name %>
</div>

<div class="field">
	<%= f.label :contact_role %>
	<%= f.text_field :contact_role %>
</div>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<%= render 'form'%>

<%= link_to 'Back', venue_contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts: <%= link_to @venue.name, venue_path(@venue) %></h1>
<%= link_to 'New Contact', new_venue_contact_path() %>
<table>
	<tr>
		<th>Contact Name</th>
		<th>Contact Role</th>
		<th>Delete</th>
		
	</tr>
	<%- for contact in @contacts %>
		<tr>
			<td><%= link_to contact.contact_name, [@venue, contact] %></td>
			<td><%= contact.contact_role %></td>
			<td><%= button_to 'Delete', [@venue, contact], :method => :delete, :confirm => "you sure?" %></td>
			
		</tr>
	<%- end%>
</table>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<h1><%= @contact.contact_name %></h1>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th width="130">Contact name:</th>
    <td><%= @contact.contact_name %> <%= link_to '(edit)', edit_venue_contact_path(@venue, @contact) %></td>
    <td><%= button_to 'Delete', [@venue, @contact], :method => :delete, :confirm => "sure?" %></td>
  </tr>
</table>