config/routes.rb
VenueManagement::Application.routes.draw do
  root :to => "venues#index"
 
  resources :venues do
    resources :contacts
    resources :styles
    resources :meeting_rooms
  end

  match 'api/search_venues(.:format)'
  match 'api/show_venue(.:format)'

end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :venue
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  # GET /styles
  # GET /styles.xml
  def index
    @venue = Venue.find(params[:venue_id])
    @styles = @venue.style
    
    respond_to do |format|
      format.html #index.html.erb
      format.xml { render :xml => @styles }
    end
  end
  
  # GET /styles/1
  # GET /styles/1.xml
  def show
    @venue = Venue.find(params[:venue_id])
    @style = @venue.style.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @style }
    end
  end

  # GET /styles/new
  # GET /styles/new.xml
  def new
    @venue = Venue.find(params[:venue_id])
    @style = @venue.style.new

    respond_to do |format|
      format.html #new.html.erb
    end
  end
  
   # GET /styles/1/edit
  def edit
    @venue = Venue.find(params[:venue_id])
    @style = @venue.style.find(params[:id])
  end
  
  # POST /styles
  # POST /styles.xml
  def create
    @venue = Venue.find(params[:venue_id])
    @style = @venue.style.new(params[:style])
    
    respond_to do |format|
      if @style.save
        format.html { redirect_to(venue_styles_path, :notice => 'style was successfully created.') }
      else
        format.html {render :action => "new" }
      end 
    end
  end
  
  # POST /styles
  # POST /styles.xml
  def update
    @venue = Venue.find(params[:venue_id])
    @style = @venue.style.find(params[:id])
        
    respond_to do |format|
      if @style.update_attributes(params[:style])
        #format.html { redirect_to(venue_styles_path, :notice => "style was successfully updated.")}
        format.html { redirect_to(venue_styles_path, :notice => "style was successfully updated.")}
        format.xml { head :ok }
       else
         format.html { render :action => "edit"}
         format.xml { render :xml => @style.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  #DELETE /styles/1
  #DELETE /styles/1.xml
  def destroy
    @venue = Venue.find(params[:venue_id])
    @style = @venue.style.find(params[:id])
    @style.destroy
    
    respond_to do |format|
      format.html { redirect_to(venue_styles_url)}
      format.xml { head :ok } 
    end
  end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for [@venue, @style] do |f| %>
	
	<% if @style.errors.any? %>
		<div id="error_explanation">
			
			<h2>Error occurred</h2>
		</div>
	<% end %>
	
<div class="field">
	<%= f.label :style%>
	<%= f.text_field :style %>
</div>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/styles/edit.html.erb
<h1>Edit Venue Style</h1>

<%= render 'form'%>

<%= link_to 'Back', venue_styles_path %>

app/views/styles/index.html.erb
<h1>Venue Style: <%= link_to @venue.name, venue_path(@venue) %> </h1>
<%= link_to 'Add Venue Style', new_venue_style_path() %>
<table>
	<tr>
		<th>Style</th>
		<th>Delete</th>
		
	</tr>
	<%- for style in @styles %>
		<tr>
			<td><%= link_to style.style, [@venue, style] %></td>
			<td><%= button_to 'Delete', [@venue, style], :method => :delete, :confirm => "you sure?" %></td>
		</tr>
	<%- end%>
</table>

app/views/styles/new.html.erb
<h1>New Venue Style</h1>

<%= render 'form' %>

app/views/styles/show.html.erb
<h1><%= link_to @venue.name, venue_path(@venue) %>: <%= @style.style %></h1>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th width="130">Venue Style:</th>
    <td><%= @style.style %> <%= link_to '(edit)', edit_venue_style_path(@venue, @style) %></td>
    <td><%= button_to 'Delete', [@venue, @style], :method => :delete, :confirm => "you sure?" %></td>
  </tr>
</table>